orgs:
  baloise:
    name: Baloise Group
    billing_email: Group.CH_Open-Source@baloise.ch
    company: ""
    default_repository_permission: read
    description: Open Source @ Baloise Group
    email: Group.CH_Open-Source@baloise.ch
    has_organization_projects: true
    has_repository_projects: true
    location: Aeschengraben 21, 4002 Basel, Switzerland
    members_can_create_repositories: true
    admins:
    - baopso
    - culmat
    - hirsch88
    - incubator-tekton
    - joachimprinzbach
    - niiku
    - patrit
    - arburk
    - kullmanp 
    - Tiliavir
    - svene
    members:
    - 6f1045
    - abrjak
    - AlainLatscha
    - Alex-Thoma
    - aMiladinovic
    - ArthurNeudeck
    - b016533
    - baengel
    - BeateGuldenschuh
    - BenjaminMueller84
    - BerSteve
    - bhaskarchenchu
    - borisrudolf
    - bsolar17
    - christiansiegel
    - MarkusTiede
    - christophgeering
    - clastzoo
    - CookieMonster70
    - CorsinSulser
    - DaOneMoD
    - dalchers
    - Dalchi
    - DanielPrill
    - davidloeffler82
    - DennisBannerman
    - didlika
    - dinupoker
    - Dr-Tech81
    - dweber019
    - ErmacoraGregor
    - Feamusbal
    - Flapmax
    - FilipMarkovski
    - Gagne87
    - Georges52
    - geschbach
    - Ginious
    - gueltekinB
    - GinaBiondo-aperto
    - harry08
    - HeikoDammeyer
    - HeinzKauer
    - hhenkel
    - honeggera
    - jacnguymesoneer
    - jenniferrupp
    - janbrohl
    - JeanDoescher
    - JelenaSretenovic
    - kuhnfe
    - klaushuberruiz
    - krzmur
    - l0r5
    - lagoaresti
    - LaurentSteiner
    - lazaki
    - lbiry
    - leubedane
    - lundak
    - lrommerskirchen
    - m4rc0z
    - manuel84
    - marcellobellini
    - MarkusFlorian79
    - mariusreusch
    - matal0
    - mbobzin
    - MegaRusher
    - MelPiw
    - MicBag
    - mikevader
    - mk-it-easy
    - mladenplaninicic
    - monkold
    - MrCode97
    - mw-solutions
    - nfricker
    - nobilo
    - NoraKurzbein
    - OlgaSchwarz
    - olivierglath
    - petramohler
    - predrag-arsic
    - r3dDoX
    - raltho
    - randeep228
    - renat1sakenov
    - reneschatz
    - Rikdewinne
    - RMarLuce
    - rolfstebler
    - rotalf
    - rothmarco
    - sauterl
    - stefan-jungo
    - simonboerlin
    - skytime-sh
    - sobabufe    
    - Solaflex
    - stefan-jungo
    - StefaanSaeys
    - stefanschoe
    - StephanSST
    - Sw0rdiX
    - thbert
    - Thomas4712
    - ThomasPBurri
    - TimonLoew
    - tommuelli
    - trichie
    - tschneichel
    - vangual
    - VasilijeRadulovic
    - yannickholzenkamp
    - YvesVdm
    - RCBiczok
    - oleg-arch
    - prevosys
    - juliafeld
    - niels-oz
    - pbadevops
    - pythaurus
    - koenigle
    - robert-groensfeld
    - tschei65
    - seejaybee
    - jdbg0e
    - udamken
    teams:
      Organization Managers:
        description: Baloise GitHub Organization Managers
        maintainers:
        - baopso
        members:
        - culmat
        - hirsch88
        - incubator-tekton
        - joachimprinzbach
        - niiku
        - patrit
        - arburk
        - kullmanp 
        - Tiliavir
        - svene
        privacy: closed
        repos:
          org: admin


      
